#/usr/lib/jvm/java-6-openjdk/bin/java -server -Xmn10m -Xms200m -Xmx2g -Ddelite.home.dir=/home/stivo/master/Delite -Ddelite.build.dir=/home/stivo/master/Delite/generated/ -Ddelite.deg.filename=epfl.apps.distributed.ToyRunner.deg -Ddelite.extern.blas -Dnested.variants.level=0 -cp '/home/stivo/master/Delite/lib_managed/jars/EPFL/lms_2.10.0-virtualized-SNAPSHOT//target/scala-2.10.0-virtualized-SNAPSHOT/classes:/home/stivo/master/Delite/lib_managed/jars/EPFL/lms_2.10.0-virtualized-SNAPSHOT//*:/home/stivo/master/Delite/framework/target/scala-2.10.0-virtualized-SNAPSHOT/classes:/home/stivo/master/Delite/dsls/optiml/target/scala-2.10.0-virtualized-SNAPSHOT/classes:/home/stivo/master/Delite/dsls/optila/target/scala-2.10.0-virtualized-SNAPSHOT/classes:/home/stivo/master/Delite/dsls/distributed/target/scala-2.10.0-virtualized-SNAPSHOT/classes:/home/stivo/master/Delite/apps/optiml/target/scala-2.10.0-virtualized-SNAPSHOT/classes:/home/stivo/master/Delite/apps/optila/target/scala-2.10.0-virtualized-SNAPSHOT/classes:/home/stivo/master/Delite/apps/optiql/target/scala-2.10.0-virtualized-SNAPSHOT/classes:/home/stivo/master/Delite/apps/distributed/target/scala-2.10.0-virtualized-SNAPSHOT/classes:/home/stivo/master/Delite/tests/target/scala-2.10.0-virtualized-SNAPSHOT/classes:/home/stivo/master/Delite/target/scala-2.10.0-virtualized-SNAPSHOT/test-classes/:/home/stivo/.sbt/boot/scala-2.10.0-virtualized-SNAPSHOT/lib//lib/scala-library.jar:/home/stivo/.sbt/boot/scala-2.10.0-virtualized-SNAPSHOT/lib//lib/scala-compiler.jar:/home/stivo/.sbt/boot/scala-2.10.0-virtualized-SNAPSHOT/lib//*' epfl.apps.distributed.ToyRunner

#to put on classpath:
#lms
#scala virtualized
#eclipse compilation
set -x
export HERE="/home/stivo/master/Delite"
export TARGET="target/scala-2.10.0-virtualized-SNAPSHOT/classes"
/usr/lib/jvm/java-6-openjdk/bin/java -server -Xmn10m -Xms200m -Xmx2g -Ddelite.home.dir=/home/stivo/master/Delite -Ddelite.build.dir=/home/stivo/master/Delite/generated/ -Ddelite.deg.filename=epfl.apps.distributed.ToyRunner.deg -Ddelite.extern.blas -Dnested.variants.level=0 -cp "/home/stivo/master/virtualization-lms-core/$TARGET:$HERE/framework/$TARGET:$HERE/dsls/distributed/$TARGET:$HERE/apps/distributed/$TARGET:/home/stivo/.sbt/boot/scala-2.10.0-virtualized-SNAPSHOT/lib/scala-library.jar:/home/stivo/.sbt/boot/scala-2.10.0-virtualized-SNAPSHOT/lib/scala-compiler.jar" epfl.apps.distributed.ToyRunner

